---
- name: Set up offsite backup on Odroid HC4.
  hosts: odroidhc4
  become: true

  roles:
    - role: openvpn-client
      vpn_user: "{{ lookup('community.general.bitwarden', '14e212a1-423a-4fa3-9476-adbb016ffe35', search='id', field='username') | first }}"
      vpn_password: "{{ lookup('community.general.bitwarden', '14e212a1-423a-4fa3-9476-adbb016ffe35', search='id', field='password') | first }}"
    - role: chriswayg.msmtp-mailer

  vars_files:
    - vars/msmtp.yml

  tasks:
    - name: Ensure ZFS is installed.
      ansible.builtin.import_tasks: tasks/armbian-zfs.yml
      vars:
        kernel_variant: edge-meson64

    - name: Import zpool if available.
      ansible.builtin.import_tasks: tasks/ensure-zpool.yml
      vars:
        pool_name: obox
        properties:
          ashift: "12"
          autoexpand: "on"
        filesystem_properties:
          atime: "off"
          compression: "lz4"
        vdevs:
          - mirror
          - ata-WDC_WD30EFRX-68AX9N0_WD-WMC1T0638111
          - ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N0M5R0YP

    - name: Ensure Avahi is installed, to advertise hostname with mDNS.
      ansible.builtin.apt:
        name: avahi-daemon
        state: present
